name: Continuous integration
on:
  pull_request:
  push:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@9de5c646b53804bb3d042eeae6cbd9a4fd433dd9
        with:
          default: true
          ldproxy: true
      - name: Release build std
        uses: actions-rs/cargo@v1
        with:
          command: build

  clippy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@9de5c646b53804bb3d042eeae6cbd9a4fd433dd9
        with:
          default: true
          ldproxy: true
      - name: Annotate commit with clippy warnings
        uses: actions-rs/clippy-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

  security-audit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Rust for Xtensa
        uses: esp-rs/xtensa-toolchain@9de5c646b53804bb3d042eeae6cbd9a4fd433dd9
        with:
          default: true
          ldproxy: true
      - name: Security audit
        uses: actions-rs/audit-check@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}

